//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mysevice", ConfigurationName="ServiceReference1.UserviceSoap")]
    public interface UserviceSoap {
        
        // CODEGEN: Generating message contract since element name MyHelloResult from namespace http://mysevice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mysevice/MyHello", ReplyAction="*")]
        WebApp1.ServiceReference1.MyHelloResponse MyHello(WebApp1.ServiceReference1.MyHelloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyHello", Namespace="http://mysevice", Order=0)]
        public WebApp1.ServiceReference1.MyHelloRequestBody Body;
        
        public MyHelloRequest() {
        }
        
        public MyHelloRequest(WebApp1.ServiceReference1.MyHelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MyHelloRequestBody {
        
        public MyHelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyHelloResponse", Namespace="http://mysevice", Order=0)]
        public WebApp1.ServiceReference1.MyHelloResponseBody Body;
        
        public MyHelloResponse() {
        }
        
        public MyHelloResponse(WebApp1.ServiceReference1.MyHelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mysevice")]
    public partial class MyHelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MyHelloResult;
        
        public MyHelloResponseBody() {
        }
        
        public MyHelloResponseBody(string MyHelloResult) {
            this.MyHelloResult = MyHelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserviceSoapChannel : WebApp1.ServiceReference1.UserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserviceSoapClient : System.ServiceModel.ClientBase<WebApp1.ServiceReference1.UserviceSoap>, WebApp1.ServiceReference1.UserviceSoap {
        
        public UserviceSoapClient() {
        }
        
        public UserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp1.ServiceReference1.MyHelloResponse WebApp1.ServiceReference1.UserviceSoap.MyHello(WebApp1.ServiceReference1.MyHelloRequest request) {
            return base.Channel.MyHello(request);
        }
        
        public string MyHello() {
            WebApp1.ServiceReference1.MyHelloRequest inValue = new WebApp1.ServiceReference1.MyHelloRequest();
            inValue.Body = new WebApp1.ServiceReference1.MyHelloRequestBody();
            WebApp1.ServiceReference1.MyHelloResponse retVal = ((WebApp1.ServiceReference1.UserviceSoap)(this)).MyHello(inValue);
            return retVal.Body.MyHelloResult;
        }
    }
}
